## This is a pair of functions allow you to cache the inverse of a matrix
## and retrieve it to avoid rerunning the very resource intensive inversion 

## makeCacheMatrix takes in a matrix object and returns a list containing
## a set and get functions for the matrix, and set and get functions for its inverse

makeCacheMatrix <- function(x = matrix()) {
  
  ## initialize w/ null invese
  i <- NULL
  
  ## get/set functions for the matrix
  set <- function(y){
    x <<- y
    i <<- Null
  }
  get <- function() x
  
  ## get/set functions for the inverse
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  
  list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)

}

## cacheSolve takes in a list object that has been generated by makeCacheMatrix
## and returns the inverse of that matrix. It first checks to see if the inverse
## has already been calculated. If it has it returns that. Otherwise it calculates
## the inverse, sets it, and then returns it

cacheSolve <- function(x, ...) {
  
  ## gets cached inverse from inputted object
  i <- x$getinverse()
  
  
  ## if this inverse has been created (is not null) it retrieves it
  if(!is.null(i)){
    message("Retrieving cached matrix.")
    return(i)
  }
  
  ## otherwise it retieves the matrix, calculates the inverse, sets it in the passed in function... 
  data <- x$get()
  i <- solve(data,...)
  x$setinverse(i)
  
  ## ...and finally returns it
  i
  
}
